# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages:
  - "commit" # run linters to prevent committing important mistakes
  - "post-commit" # auto-format and warn about style mistakes
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: mixed-line-ending
  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black
        name: black (python)
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/PyCQA/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        args: ["--ignore=E501"]
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.5"
    hooks:
    - id: bandit
      args: ["--skip", "B101", "-r", "."]
